export { AuthOtpSchema } from "./auth-otp.entity";
export type { AuthOtpEntity } from "./auth-otp.entity";
export { ParkingUserSchema } from "./parking-user.entity";
export type { ParkingUserEntity, ParkingUserRole } from "./parking-user.entity";
export { ParkingSettingSchema } from "./parking-setting.entity";
export type { ParkingSettingEntity } from "./parking-setting.entity";
export { VisitorTypeSchema } from "./visitor-type.entity";
export type { VisitorTypeEntity } from "./visitor-type.entity";
export { VisitorSchema } from "./visitor.entity";
export type { VisitorEntity, VisitorStatus } from "./visitor.entity";
export { VisitorScanEventSchema } from "./visitor-scan-event.entity";
export type { VisitorScanEventEntity, VisitorScanEventType } from "./visitor-scan-event.entity";
export { VehicleSchema } from "./vehicle.entity";
export type { VehicleEntity } from "./vehicle.entity";
